--- Cows: Placeholder flags for main options / sandbox options...
-- IsDebugModeActive = true;
-- IsInfiniteAmmoActive = true;
-- IsNPCsNeedsActive = false;
-- IsPVPActive = false;
-- GroupSizeLimit = 8;
